config {
    type: "incremental",
    protected: true,
    description: "db_work_order_dtl dimension table",
    uniqueKey: ["Work_Ord_Dtl_Id", "Valid_From_Dt", "Fin_Rep_Valid_From_Mth"],
    bigquery: {
        partitionBy: "TIMESTAMP_TRUNC(UPDATE_LOAD_TS, MONTH)"
    },
    tags: ["Semantic", "Dimension", "db_work_order_dtl"]
}

pre_operations {
  delete from ${self()} where true;
--  SELECT ERROR("Cannot write NULL to Conv_Status_Dt field");
}

SELECT CAST(stg_s_order_item_hist_db_wod_90.Work_Ord_Dtl_Id AS STRING) AS Work_Ord_Dtl_Id,
       CAST(stg_s_order_item_hist_db_wod_90.Valid_From_Dt AS DATE) AS Valid_From_Dt,
       CAST(stg_s_order_item_hist_db_wod_90.Valid_Until_Dt AS DATE) AS Valid_Until_Dt,
       CAST(stg_s_order_item_hist_db_wod_90.Current_Ind AS STRING) AS Current_Ind,
       CAST(stg_s_order_item_hist_db_wod_90.Ident_Type_Cd AS STRING) AS Ident_Type_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Ident_1_Num AS STRING) AS Ident_1_Num,
       CAST(stg_s_order_item_hist_db_wod_90.Ident_2_Num AS STRING) AS Ident_2_Num,
       CAST(stg_s_order_item_hist_db_wod_90.Ident_3_Num AS STRING) AS Ident_3_Num,
       CAST(stg_s_order_item_hist_db_wod_90.Ident_4_Num AS STRING) AS Ident_4_Num,
       CAST(stg_s_order_item_hist_db_wod_90.Ident_5_Num AS STRING) AS Ident_5_Num,
       CAST(stg_s_order_item_hist_db_wod_90.Action_Type_Cd AS STRING) AS Action_Type_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Conv_Status_Cd AS STRING) AS Conv_Status_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Conv_Status_Dt AS DATE) AS Conv_Status_Dt,
       CAST(stg_s_order_item_hist_db_wod_90.Action_Rsn_Cd AS STRING) AS Action_Rsn_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Action_Sub_Rsn_Cd AS STRING) AS Action_Sub_Rsn_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Rejected_Rsn_Cd AS STRING) AS Rejected_Rsn_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Work_Ord_Id AS STRING) AS Work_Ord_Id,
       CAST(stg_s_order_item_hist_db_wod_90.Alt_Work_Ord_Id AS STRING) AS Alt_Work_Ord_Id,
       CAST(stg_s_order_item_hist_db_wod_90.Servng_Sale_Org_Id AS STRING) AS Servng_Sale_Org_Id,
       CAST(stg_s_order_item_hist_db_wod_90.Promtn_Id AS STRING) AS Promtn_Id,
       CAST(stg_s_order_item_hist_db_wod_90.Serv_Offer_Id AS STRING) AS Serv_Offer_Id,
       CAST(stg_s_order_item_hist_db_wod_90.Prod_Seq_Num AS STRING) AS Prod_Seq_Num,
       CAST(stg_s_order_item_hist_db_wod_90.Cancel_Req_Type_Cd AS STRING) AS Cancel_Req_Type_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Plan_Final_Dt AS DATE) AS Plan_Final_Dt,
       CAST(stg_s_order_item_hist_db_wod_90.Serv_Offer_Cnt AS INT64) AS Serv_Offer_Cnt,
       CAST(stg_s_order_item_hist_db_wod_90.LOB_Cd AS STRING) AS LOB_Cd,
       CAST(stg_s_order_item_hist_db_wod_90.Fin_Rep_Valid_From_Mth AS INT64) AS Fin_Rep_Valid_From_Mth,
       CAST(stg_s_order_item_hist_db_wod_90.Fin_Rep_Valid_Until_Mth AS INT64) AS Fin_Rep_Valid_Until_Mth,
       CAST(format_timestamp('%Y%m%d%H%M%S', CURRENT_TIMESTAMP()) AS INT64) AS Insert_Load_Id,
       CAST(format_timestamp('%Y%m%d%H%M%S', CURRENT_TIMESTAMP()) AS INT64) AS Update_Load_Id,
       COALESCE(UPDATE_LOAD_TS, CAST('1900-01-01 00:00:00' AS TIMESTAMP)) AS UPDATE_LOAD_TS
FROM   ${ref("stg_s_order_item_hist_db_wod_90")} stg_s_order_item_hist_db_wod_90


