config {
    type: "table",
    description: "db_test dimension table",
    tags: ["Semantic", "Dimension", "db_test"]
}


SELECT CAST(stg_s_customer_90.Cust_ID AS STRING) AS Cust_ID,
       CAST(stg_s_customer_90.Valid_From_Dt AS DATE) AS Valid_From_Dt,
       CAST(stg_s_customer_90.Valid_Until_Dt AS DATE) AS Valid_Until_Dt,
       CAST(stg_s_customer_90.Ident_Type_Cd AS STRING) AS Ident_Type_Cd,
       CAST(stg_s_customer_90.Ident_1_Num AS STRING) AS Ident_1_Num,
       CAST(stg_s_customer_90.Insert_Load_Id AS STRING) AS Insert_Load_Id,
       CAST(stg_s_customer_90.Update_Load_Id AS STRING) AS Update_Load_Id
 FROM   ${ref("stg_s_customer_90")} stg_s_customer_90